import os
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import albumentations as A
from albumentations.pytorch import ToTensorV2

from model import AttentionUNet

# Parameters (Must match train.py exactly)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
CHECKPOINT_PATH = "checkpoint_20.pth.tar"
NUM_CLASSES = 3
TEST_IMG_DIR = "data/images/"  # Change to data/val_images/ if using a separate split folder
TEST_MASK_DIR = "data/masks/"

def color_code_mask(mask_2d):
    """Converts a 2D class index mask (0, 1, 2) into an RGB image for visualization."""
    h, w = mask_2d.shape
    rgb_mask = np.zeros((h, w, 3), dtype=np.uint8)
    
    # Define colors for your classes
    # Class 0 (Background) = Black [0, 0, 0]
    rgb_mask[mask_2d == 1] = [255, 0, 0]   # Class 1 (Circle) = Red
    rgb_mask[mask_2d == 2] = [0, 0, 255]  # Class 2 (Square) = Blue
    
    return rgb_mask

def visual_inference_multiclass():
    # 1. Initialize model
    model = AttentionUNet(in_channels=3, out_channels=NUM_CLASSES).to(DEVICE)    
    # Load raw checkpoint dictionary
    checkpoint = torch.load(CHECKPOINT_PATH, map_location=DEVICE)
    state_dict = checkpoint["state_dict"]
    
    # FIX: Strip "_orig_mod." prefix generated by torch.compile from checkpoint keys
    clean_state_dict = {}
    for key, value in state_dict.items():
        if key.startswith("_orig_mod."):
            clean_state_dict[key.replace("_orig_mod.", "")] = value
        else:
            clean_state_dict[key] = value

    # Load the cleaned state dict into your model layers
    model.load_state_dict(clean_state_dict)
    model.eval()

    # 2. Get the first image file
    images = [f for f in os.listdir(TEST_IMG_DIR) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
    if not images:
        print("No images found to test.")
        return
    
    test_file = images[0]
    img_path = os.path.join(TEST_IMG_DIR, test_file)
    mask_path = os.path.join(TEST_MASK_DIR, test_file)

    # 3. Load raw images
    raw_image = Image.open(img_path).convert("RGB")
    raw_mask = Image.open(mask_path).convert("L")

    transform = A.Compose([
        A.Resize(height=256, width=256),
        A.Normalize(mean=[0.0, 0.0, 0.0], std=[1.0, 1.0, 1.0], max_pixel_value=255.0),
        ToTensorV2(),
    ])
    
    # Transform image for network input
    augmented = transform(image=np.array(raw_image))
    input_tensor = augmented["image"].unsqueeze(0).to(DEVICE)

    # 4. Forward Pass
    with torch.no_grad():
        logits = model(input_tensor)
        preds = torch.argmax(logits, dim=1) 
    
    # Convert tensors back to viewable numpy arrays
    pred_mask_2d = preds.squeeze().cpu().numpy()
    true_mask_2d = np.array(raw_mask.resize((256, 256)))

    # Apply RGB color coding maps
    rgb_pred_mask = color_code_mask(pred_mask_2d)
    rgb_true_mask = color_code_mask(true_mask_2d)

    # 5. Plot Side-by-Side Comparison
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    axes[0].imshow(raw_image.resize((256, 256)))
    axes[0].set_title("Original Image")
    axes[0].axis("off")

    axes[1].imshow(rgb_true_mask)
    axes[1].set_title("Ground Truth (Color Coded)")
    axes[1].axis("off")

    axes[2].imshow(rgb_pred_mask)
    axes[2].set_title("AI Multi-Class Prediction (mIoU: 0.99)")
    axes[2].axis("off")

    plt.tight_layout()
    plt.savefig("multiclass_segmentation_output.png")
    print("Inference complete! Output saved as 'multiclass_segmentation_output.png'")

if __name__ == "__main__":
    visual_inference_multiclass()